import Layout from "@/components/layout/Layout";
import Head from "next/head";

const About = () => {
	return (
		<>
			<Head>
				<title>About</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				<div className="container">All About</div>
			</Layout>
		</>
	);
};

export default About;
