import Article from "@/components/article/Article";
import Layout from "@/components/layout/Layout";
import Head from "next/head";

const Articles = () => {
	return (
		<>
			<Head>
				<title>Articles</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				<Article />
			</Layout>
		</>
	);
};

export default Articles;
