import ContactComponent from "@/components/contact/ContactComponent";
import Layout from "@/components/layout/Layout";
import Head from "next/head";

const Contact = () => {
	return (
		<>
			<Head>
				<title>Project</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				<ContactComponent />
			</Layout>
		</>
	);
};

export default Contact;
