import Layout from "@/components/layout/Layout";
import Talk from "@/components/talk/Talk";
import Head from "next/head";
const Talks = () => {
	return (
		<>
			<Head>
				<title>Talks</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				<Talk />
			</Layout>
		</>
	);
};

export default Talks;
